name: cypress-test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [19]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if component test files exist
        id: check-component-files
        run: |
          if [[ $(find vite-project/cypress/component-tests \( -name '*.cy.js' -o -name '*.cy.jsx' -o -name '*.cy.ts' -o -name '*.cy.tsx' \) | wc -l) -gt 0 ]]; then
            echo "component_file_exists=true" >> $GITHUB_ENV
          else
            echo "component_file_exists=false" >> $GITHUB_ENV
          fi
      - name: Cypress Component run
        if: env.component_file_exists == 'true'
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          working-directory: vite-project
          cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
          component: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if e2e test files exist
        id: check-e2e-files
        run: |
          if [[ $(find vite-project/cypress/e2e-tests \( -name '*.cy.js' -o -name '*.cy.jsx' -o -name '*.cy.ts' -o -name '*.cy.tsx' \) | wc -l) -gt 0 ]]; then
            echo "e2e_file_exists=true" >> $GITHUB_ENV
          else
            echo "e2e_file_exists=false" >> $GITHUB_ENV
          fi
      - name: Cypress E2E run
        if: env.e2e_file_exists == 'true'
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          working-directory: vite-project
          cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
